defaults:
  - env/realworld_peg_insertion@env.train
  - env/realworld_peg_insertion@env.eval
  - model/cnn_policy@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 2
  component_placement:
    actor: 
      node_group: "4090"
      placement: 0-0
    env:
      node_group: franka
      placement: 0-0
    rollout:
      node_group: "4090"
      placement: 0-0
  node_groups:
    - label: "4090"
      node_ranks: 0-0
      env_configs:
        - node_ranks: 0-0
          python_interpreter_path: /path/to/python
          env_vars:
            - GLOO_SOCKET_IFNAME: "eno1"
    - label: franka
      node_ranks: 1-1
      env_configs:
        - node_ranks: 1-1
          python_interpreter_path: /path/to/python
          env_vars:
            - GLOO_SOCKET_IFNAME: enp5s0
      hardware:
        type: Franka
        configs:
          - robot_ip: robot_ip
            disable_validate: True
            node_rank: 1

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "sac_mlp"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 8000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: -1
  seq_length: 4096
  max_prompt_length: 30

algorithm:
  update_epoch: 32
  auto_reset: True
  ignore_terminations: True
  use_fixed_reset_state_ids: False
  group_size: 1
  agg_q: min

  rollout_epoch: 1
  eval_rollout_epoch: 1

  adv_type: embodied_sac
  loss_type: embodied_sac
  loss_agg_func: "token-mean"
  
  bootstrap_type: always
  gamma: 0.8
  tau: 0.01  # Soft update coefficient for target networks
  auto_entropy_tuning: True  # Enable automatic entropy tuning
  alpha_type: softplus
  initial_alpha: 0.01  # Initial temperature value
  target_entropy: -4  # Target entropy (-action_dim)
  alpha_lr: 3.0e-4  # Learning rate for temperature parameter
  
  # Replay buffer settings
  replay_buffer_capacity: 100000
  min_buffer_size: 0  # Minimum buffer size before training starts
  target_update_freq: 1  # Frequency of target network updates

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

  train:
    total_num_envs: 1
    override_cfg:
      is_dummy: True
      target_ee_pose: [0, 0, 0, 0, 0, 0]
  
  eval:
    total_num_envs: 1
    override_cfg:
      is_dummy: True
      target_ee_pose: [0, 0, 0, 0, 0, 0]


rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: ""
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"

  checkpoint_load_path: ""
  checkpoint_save_path: "../results"

  micro_batch_size: 1024
  global_batch_size: 1024
  seed: 1234
  enable_offload: False

  model:
    image_keys: ["wrist_1", ]
    state_dim: 19
    action_dim: 6

  optim:
    lr: 3.0e-4  # Lower learning rate for SAC
    value_lr: 3.0e-4  # Q-network learning rate
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    clip_grad: 10.0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
