simulator_type: maniskill
auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
use_rel_reward: True
reward_mode: raw
seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
max_episode_steps: 50
only_eval: False

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "PickCube-v1"
  num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}
  obs_mode: "state"
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 100
    control_freq: 20
  max_episode_steps: ${env.train.max_episode_steps}
  sensor_configs:
    shader_pack: "default"
  render_mode: all
