simulator_type: realworld

total_num_envs: null

auto_reset: True
ignore_terminations: True
reward_mode: raw
wrap_obs_mode: simple
seed: 0
group_size: 1
use_fixed_reset_state_ids: False
max_steps_per_rollout_epoch: 100
max_episode_steps: 100
use_spacemouse: True

# Placeholder for dummy realworld env
# If camera and robot are connected, will be overriden in the code
robot_ip: 0.0.0.0
camera_serials: ["0123456789", ]


video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "PegInsertionEnv-v1"
  num_envs: null

